version: '3.8'

services:
  app:
    image: employee-management
    build: .
    container_name: employee-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILE=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/employee_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: employee_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
